"""Human-readable and machine-readable report rendering."""

from __future__ import annotations

import json

from .models import ScanReport


def render_terminal(report: ScanReport, *, color: bool = True) -> str:
    green = "\033[32m" if color else ""
    red = "\033[31m" if color else ""
    bold = "\033[1m" if color else ""
    reset = "\033[0m" if color else ""
    lines = [
        f"{bold}oss-ready{reset}  {report.root}",
        f"Score: {bold}{report.score}/100 ({report.grade}){reset}  "
        f"Checks: {report.passed} passed, {report.failed} failed",
        "",
    ]
    current_category = None
    for result in report.results:
        if result.category != current_category:
            if current_category is not None:
                lines.append("")
            current_category = result.category
            lines.append(f"{bold}{current_category}{reset}")
        marker = f"{green}PASS{reset}" if result.passed else f"{red}FAIL{reset}"
        required = " [required]" if result.required else ""
        lines.append(
            f"  {marker}  {result.title}{required} "
            f"({result.points}/{result.max_points})"
        )
        lines.append(f"        {result.detail}")
        if result.recommendation:
            lines.append(f"        Fix: {result.recommendation}")

    if report.required_failures:
        lines.extend(
            [
                "",
                f"{red}{bold}Required checks need attention:{reset} "
                + ", ".join(item.id for item in report.required_failures),
            ]
        )
    return "\n".join(lines) + "\n"


def render_markdown(report: ScanReport) -> str:
    lines = [
        "# oss-ready report",
        "",
        f"**Score:** {report.score}/100 ({report.grade})  ",
        f"**Checks:** {report.passed} passed, {report.failed} failed  ",
        f"**Repository:** `{report.root}`",
        "",
        "| Status | Check | Category | Points |",
        "|:--:|---|---|--:|",
    ]
    for result in report.results:
        status = "✅" if result.passed else "❌"
        required = " (required)" if result.required else ""
        lines.append(
            f"| {status} | {result.title}{required} | {result.category} | "
            f"{result.points}/{result.max_points} |"
        )

    failures = [result for result in report.results if not result.passed]
    if failures:
        lines.extend(["", "## Recommended next steps", ""])
        for result in failures:
            lines.append(f"- **{result.title}:** {result.recommendation}")
    lines.extend(["", "_Generated by [oss-ready](https://github.com/CatCat0323/oss-ready)._"])
    return "\n".join(lines) + "\n"


def render_json(report: ScanReport) -> str:
    return json.dumps(report.to_dict(), indent=2, ensure_ascii=False) + "\n"

